### ISSUE TITLE
Incorrect MAX CPU Power

### ISSUE THREAD

**Issue by Deepcuts** [openhardwaremonitor/openhardwaremonitor#1047]
Using 0.8.0 beta

CPU package,Cores and DRAM max values are scary.
See image
![image](https://user-images.githubusercontent.com/4704834/33299135-edcac072-d3f2-11e7-8ff2-9ef4b8c7aec6.png)

**Comment by DarthDestroyer** [comment]
Could you provide us a Report? That would be great!

**Comment by Deepcuts** [comment]
Complete report:
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1509568/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment]
could you try the latest Version, too?

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

**Comment by Deepcuts** [comment]
2 days on 0.8.0.3 and I didn't see the problem anymore.
Closing for now.

**Comment by chupacabras** [comment]
I have the same problem. I tried 0.8.0beta and 0.8.0.3alpha, the problem is in both versions. I have Windows 7.
Maybe it relates to hibernating. I have launched OpenHardwareMonitor all the time. Those incorrect values are shown maybe after computer is waken up from hibernation (deep sleep to disk).
![2019-04-03 08_02_33-Open Hardware Monitor]
(https://user-images.githubusercontent.com/1724077/55456484-6f9edf80-55e7-11e9-9406-8bcbf942b393.png)
![2019-04-03 08_07_22-About](https://user-images.githubusercontent.com/1724077/55456529-8ba28100-55e7-11e9-97c3-5fa8b05ee482.png)
