### ISSUE TITLE
Please add support for Asus Maximus IV Extreme-Z

### ISSUE THREAD

**Issue by Banana-97** [openhardwaremonitor/openhardwaremonitor#1235]
There are sensors missing from OHM mainly opt-temp (temperature from optional temperature probe with is installed) and opt-fan RPM which are shown in HWinfo, and Ai Suite II but not OHM (all versions).

ASUS Maximus IV Extreme-Z is using Nuvoton NCT6776F chipset.

**Comment by moellerm** [comment]
Can your run OHM and HWinfo in parallel, take a screenshot of HWinfo sensors page and save a report with OHM (File -> Save Report...)?
I can take a look if there is something obvious missing in OHM.

**Comment by Banana-97** [comment]
> Can your run OHM and HWinfo in parallel, take a screenshot of HWinfo sensors page and save a report with OHM (File -> Save Report...)?
> I can take a look if there is something obvious missing in OHM.

Here are the files, I have included HWiNFO report too if that helps. Sensors which are missing is under the ASUS Maximus IV Extreme-Z (Asus ROG) tab on HWiNFO.

[HWiNFO Log.LOG](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4302950/HWiNFO.Log.LOG)
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4302951/OpenHardwareMonitor.Report.txt)
![HWiNFO   OHM](https://user-images.githubusercontent.com/61918431/76158314-9f3b5d80-614f-11ea-977a-3440a0b2b21d.PNG)

**Comment by moellerm** [comment]
Thank you for the report and screenshot. Unfortunately I have no idea where to get the "ASUS ROG" sensor values. In order to implement this we need some documentation about the hardware (chip type) and/or the data access interface used. 

I'm closing this issue, because it can't be fixed without the missing info. If any clue about the "ASUS ROG" part shows up, don't hesitate to post here, and I will reopen the issue.
