### ISSUE TITLE
Config File resets to default

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#622]
```
If the OS crashes, or shutdown forces open hardware monitor to abruptly close, 
on the next boot settings will be lost. The Gadget, Plot, renaming of sensors 
will all be set to default. Current work around is to save a copy of 
'OpenHardwareMonitor.config' in case this happens.
```

Original issue reported on code.google.com by `jason.mc...@gmail.com` on 2 Oct 2014 at 6:12
- Merged into: #501

**Comment by Shadowmeph** [comment]
I have the exact same problems this for me usually happens when I first install this but after a while it usually fixes it self , but this time it seems to always reset to default after my win 10 PC reboots . I have set it up and then rebooted and it resets so far I have rebooted 7 times and it has reset each time, this hasnt happened on my other win 10 PCs or laptop not sure whats going on :(
