### ISSUE TITLE
Fans speeds wrong: ASUS Z87A with NCT6791D

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#654]
```
Fanspeeds start with correct values and turn wrong to 65535 after some seconds 
and than stay at these wrong values

V0.7.1 Beta, Win7 Home Premium 64Bit

Monitor.Report is attached.

```

Original issue reported on code.google.com by `DSS...@googlemail.com` on 11 Jan 2015 at 5:11

Attachments:
* [OpenHardwareMonitor.Report.txt](https://storage.googleapis.com/google-code-attachments/open-hardware-monitor/issue-654/comment-0/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment]
You should not run ASUS AI Suite in parallel, because the hardware access might not be synchronized.

It seems that the ASUS AI Suite locks the hardware monitor i/o space after access. The latest alpha version of the Open Hardware Monitor should fix this problem. See as well issue #733.

http://openhardwaremonitor.org/files/openhardwaremonitor-v0.7.1.1-alpha.zip
