### ISSUE TITLE
Can't safely remove external hard drive

### ISSUE THREAD

**Issue by sycorax** [openhardwaremonitor/openhardwaremonitor#931]
If OpenHardwareMonitor is running I can't safely remove my external hard drives. Windows says they are in use. If I close OHM, then it lets me.

**Comment by DarthDestroyer** [comment]
#924 is the nearly the same issue! hope it helps...

**Comment by sycorax** [comment]
Yes! It works by disabling HDD controllers. Thanks.

Nonetheless I think OHM shouldn't hold HDD from removal.
I saw the same issue is with USB flashes.

**Comment by DarthDestroyer** [comment]
The problem is, ohm needs online devices to check them! 
It is the same with Notebooks and there dedicated gpu, if it sleeps it will never put any data out! 

hope you get, what i mean... 

i dont know, if windows give us the ability to check when you want to safely remove a hdd... or let them sleep...

For now: If you want data, it has to be enabled and cant be removed :-(

**Comment by sycorax** [comment]
Ok, maybe just keep an open ear if Windows provides some solution.
Thank you and keep the good work :)
